version: 0.0
os:  linux
files:
  - source: /
    destination: /home/ubuntu/MovieFuelBackend
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/app_stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/post_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
      runas: root


